import { NextResponse } from 'next/server';
import { getChatContext } from '../../../lib/db';

const SYSTEM_PROMPT = `You are an elite Threat Intelligence Chat Assistant built for the ECI (Ecosystem Change Intelligence) system.
You help fraud operations and risk engineers understand recent Android security vulnerabilities and changes.

You are provided with:
1. SYSTEM PIPELINE STATUS: Operational metrics.
2. RECENT ACTION TICKETS: Top critical recommendations generated by the coordinator agent.
3. RECENT CHANGES: Raw change events detected across monitored sources.

Rules:
- Answer directly without filler like "Based on the evidence provided".
- If asked about overall system state or critical vulnerabilities, use the ACTION TICKETS.
- If asked about specific CVEs, APIs, or components, use RECENT CHANGES.
- If asked about operational metrics, use SYSTEM PIPELINE STATUS.
- Cite change IDs (e.g. change_82) when referencing specific intel.
- Format responses with markdown (bullet points, bold text).
- If information is not in the provided context, say so clearly.`;

export async function POST(request) {
  try {
    const { query: userQuery } = await request.json();

    if (!userQuery?.trim()) {
      return NextResponse.json({ response: 'Please enter a question.' }, { status: 400 });
    }

    const groqApiKey = process.env.GROQ_API_KEY;
    if (!groqApiKey) {
      return NextResponse.json({ response: 'Error: GROQ_API_KEY is not configured.' }, { status: 500 });
    }

    const { stats, ticketsText, changesText } = await getChatContext();

    const userPrompt = `=== SYSTEM PIPELINE STATUS ===
${stats}

=== RECENT ACTION TICKETS ===
${ticketsText}

=== RECENT CHANGES ===
${changesText}

=== USER QUERY ===
${userQuery}`;

    const groqResponse = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${groqApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'llama-3.1-8b-instant',
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: userPrompt },
        ],
        temperature: 0.1,
        max_tokens: 1024,
      }),
    });

    if (!groqResponse.ok) {
      const err = await groqResponse.text();
      throw new Error(`Groq API error: ${err}`);
    }

    const data = await groqResponse.json();
    const answer = data.choices?.[0]?.message?.content?.trim() || 'No response generated.';

    return NextResponse.json({ response: answer });

  } catch (error) {
    console.error('Chat error:', error);
    return NextResponse.json(
      { response: `Error: ${error.message}` },
      { status: 500 }
    );
  }
}
