import { NextResponse } from 'next/server';
import { query } from '../../../lib/db';

const SYSTEM_PROMPT = `You are an elite Threat Intelligence Chat Assistant built for the ECI (Ecosystem Change Intelligence) system.
You help fraud operations and risk engineers understand recent Android security vulnerabilities and changes.

You are provided with:
1. SYSTEM PIPELINE STATUS: Operational metrics.
2. RECENT ACTION TICKETS: Top critical recommendations generated by the coordinator agent.
3. RECENT CHANGES: Raw change events detected across monitored sources.

Rules:
- Answer directly without filler like "Based on the evidence provided".
- If asked about overall system state or critical vulnerabilities, use the ACTION TICKETS.
- If asked about specific CVEs, APIs, or components, use RECENT CHANGES.
- If asked about operational metrics, use SYSTEM PIPELINE STATUS.
- Cite change IDs (e.g. change_82) when referencing specific intel.
- Format responses with markdown (bullet points, bold text).
- If information is not in the provided context, say so clearly.`;

async function getPipelineContext() {
  try {
    const [sourcesRow] = await query('SELECT COUNT(*) as count FROM sources WHERE active = true');
    const [changesRow] = await query('SELECT COUNT(*) as count FROM changes');
    const [pendingRow] = await query("SELECT COUNT(*) as count FROM changes WHERE status = 'pending'");
    const [escalatedRow] = await query("SELECT COUNT(*) as count FROM changes WHERE status = 'escalated'");

    const stats = `Active Sources Monitored: ${sourcesRow.count}
Total Changes Detected: ${changesRow.count}
Pending Changes: ${pendingRow.count} | Escalated Changes: ${escalatedRow.count}`;

    const tickets = await query(`
      SELECT r.title, r.summary, r.priority, r.risk_score, s.name as source_name
      FROM recommendations r
      LEFT JOIN changes c ON r.change_id = c.id
      LEFT JOIN sources s ON c.source_id = s.id
      ORDER BY r.risk_score DESC LIMIT 10
    `);

    const ticketsText = tickets.length > 0
      ? tickets.map(t => `Ticket: [${t.priority?.toUpperCase()}] ${t.title} (Risk: ${t.risk_score}, Source: ${t.source_name})\nSummary: ${t.summary}`).join('\n\n')
      : 'No action tickets found.';

    const changes = await query(`
      SELECT c.id, c.diff_text, c.status, s.name as source_name, s.category
      FROM changes c
      LEFT JOIN sources s ON c.source_id = s.id
      ORDER BY c.id DESC LIMIT 10
    `);

    const changesText = changes.length > 0
      ? changes.map(c => `[change_${c.id}] (${c.source_name}, ${c.category}, status: ${c.status})\n${c.diff_text?.substring(0, 300) || 'No diff text'}`).join('\n\n')
      : 'No recent changes found.';

    return { stats, ticketsText, changesText };
  } catch (e) {
    return { stats: 'Unavailable', ticketsText: 'Unavailable', changesText: 'Unavailable' };
  }
}

export async function POST(request) {
  try {
    const { query: userQuery } = await request.json();

    if (!userQuery?.trim()) {
      return NextResponse.json({ response: 'Please enter a question.' }, { status: 400 });
    }

    const groqApiKey = process.env.GROQ_API_KEY;
    if (!groqApiKey) {
      return NextResponse.json({ response: 'Error: GROQ_API_KEY is not configured.' }, { status: 500 });
    }

    const { stats, ticketsText, changesText } = await getPipelineContext();

    const userPrompt = `=== SYSTEM PIPELINE STATUS ===
${stats}

=== RECENT ACTION TICKETS ===
${ticketsText}

=== RECENT CHANGES ===
${changesText}

=== USER QUERY ===
${userQuery}`;

    const groqResponse = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${groqApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'llama-3.1-8b-instant',
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: userPrompt },
        ],
        temperature: 0.1,
        max_tokens: 1024,
      }),
    });

    if (!groqResponse.ok) {
      const err = await groqResponse.text();
      throw new Error(`Groq API error: ${err}`);
    }

    const data = await groqResponse.json();
    const answer = data.choices?.[0]?.message?.content?.trim() || 'No response generated.';

    return NextResponse.json({ response: answer });

  } catch (error) {
    console.error('Chat error:', error);
    return NextResponse.json(
      { response: `Error: ${error.message}` },
      { status: 500 }
    );
  }
}
