import json
from groq import Groq
from config.settings import GROQ_API_KEY, LLM_MODEL, LLM_TEMPERATURE
from rag.retriever import retrieve_graph_rag, retrieve_recent_tickets, retrieve_pipeline_stats

CHAT_SYSTEM_PROMPT = """You are an elite Threat Intelligence Chat Assistant built specifically for the ECI ecosystem.
You are helping fraud operations and risk engineers understand recent vulnerabilities and changes.

You are provided with three contexts:
1. SYSTEM PIPELINE STATUS: Operational metrics.
2. RECENT SYSTEM ACTION TICKETS: The top critical recommendations generated by the coordinator.
3. GRAPH-RAG EVIDENCE & HISTORICAL INTELLIGENCE: Raw intelligence chunks returned via vector search.

Given the USER QUERY and the provided contexts, give a concise, confident, and professional response.
- If the user asks about the overall system state, current critical vulnerabilities, or threat overview, answer using the RECENT SYSTEM ACTION TICKETS.
- If the user asks a specific technical or historical question about a CVE, product, or API, rely heavily on GRAPH-RAG EVIDENCE.
- If the user asks about operational metrics (how many things we track, what is pending), use SYSTEM PIPELINE STATUS.
- Start directly with the answer. Do not use filler openings like "Based on the evidence provided".
- Explicitly cite the Evidence IDs (e.g. change_82) in brackets when referencing specific intel.
- If the answer is not in the provided evidence, formulate the best answer you can but warn the user that you could not find explicitly matching historical records.
- Format your response cleanly using markdown (bullet points, bold text)."""

def answer_query(query_text: str) -> str:
    """Answers a user query using the hybrid Graph-RAG system."""
    if not GROQ_API_KEY:
        return "Error: GROQ API key is missing. Cannot invoke the LLM."
        
    client = Groq(api_key=GROQ_API_KEY)
    
    # Retrieve evidence using the same graph-rag logic as the coordinator
    try:
        cross_context = retrieve_graph_rag(query_text, source_id=None, top_k=5)
        recent_tickets = retrieve_recent_tickets(top_k=10)
        pipeline_stats = retrieve_pipeline_stats()
    except Exception as e:
        return f"Error retrieving evidence from the engine: {e}"
        
    user_prompt = f"""=== SYSTEM PIPELINE STATUS ===
{pipeline_stats}

=== RECENT SYSTEM ACTION TICKETS ===
{recent_tickets}

=== GRAPH-RAG EVIDENCE & HISTORICAL INTELLIGENCE ===
{cross_context['formatted_context']}

=== USER QUERY ===
{query_text}"""

    try:
        response = client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": CHAT_SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            temperature=LLM_TEMPERATURE,
            max_tokens=1024,
        )
        
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"Error generating response from LLM: {e}"

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        q = " ".join(sys.argv[1:])
        print(answer_query(q))
    else:
        print("Usage: python chat.py '<query>'")
